### ISSUE TITLE
When clicking hyperlink on page enable "open new tab" instead of redirecting.

### ISSUE THREAD

**Issue by P3ter-NEARWEEK** [NEAR-labs/labs-worklog#134]
## 📋   Anything to add?

Currently when clicking a link user is taken away from homepage. Instead we want a new tab to open in browser when user clicks on a link.

## 🎉   Subtasks

- [ ] 
- [ ] 
- [ ] 

## 🤼‍♂️   Reviewer

@caroline93

**Comment by P3ter-NEARWEEK** [comment]
When a link is clicked on the "editions page" (http://5.161.56.222/newsletter/edition-43) user is still taken away, a new tab doesn't open @caroline93 

<img width="810" alt="Screenshot 2022-06-06 at 20 01 36" src="https://user-images.githubusercontent.com/89806831/172218845-149502c9-ca84-458e-9591-1efa82b137bf.png">

**Comment by caroline93** [comment]
Done, please check
