### ISSUE TITLE
Test of KYC Trulio

### ISSUE THREAD

**Issue by caroline93** [NEAR-labs/labs-worklog#135]
## 📋   Anything to add?

Please check if it works correct.
## 🎉   Subtasks

Links for tasting:
https://nicepay.beskyd.com:8086/ede6bf79b5314371aeda432558522369/
https://nicepay.beskyd.com:8086/82402360d2c1487095700b2939fe5217/
https://nicepay.beskyd.com:8086/ab08035a73cc48b9bb57751e0fd8b0ff/
https://nicepay.beskyd.com:8086/717b49dea6e84955a800fd3beb198ff8/
https://nicepay.beskyd.com:8086/c34cdf3dc57a44aaafb170939548cc54/
https://nicepay.beskyd.com:8086/754eda9f91a446eb95bdf1e8154c264b/
https://nicepay.beskyd.com:8086/815be37bb7ea4c0c930cf2bc6bb5533e/
https://nicepay.beskyd.com:8086/2b9c8075f9a64ab8819ecc5f557f39f6/
https://nicepay.beskyd.com:8086/4ff8f269c7bb446fb29feb9e24cc515d/
https://nicepay.beskyd.com:8086/2b6bb3da402a4f27a12cc140d6c76e3e/
https://nicepay.beskyd.com:8086/b7ea0b65dfef4fc0ad91c16a2234c400/
https://nicepay.beskyd.com:8086/00c512135e0245e69eda613a72607613/
https://nicepay.beskyd.com:8086/2a30d6273b5545a69718fe6514d92760/
https://nicepay.beskyd.com:8086/35a6a3c372d844d4beaa6913364fb9ef/
https://nicepay.beskyd.com:8086/d38572397a8d49ca89c9e07e7286e138/
https://nicepay.beskyd.com:8086/82039db4d5324288a4d30d9ba47833c5/
https://nicepay.beskyd.com:8086/bc51c949000a4cec829f6316aae9cdf6/
https://nicepay.beskyd.com:8086/0c2d493e0e7842da840320cbd0c99e2b/
https://nicepay.beskyd.com:8086/735b3c72203b4e6ca197ae53f29f3eb9/
https://nicepay.beskyd.com:8086/5aff6de7982b4f21a356f815b831b13f/
## 🤼‍♂️   Reviewer

@

**Comment by Leobios** [comment]
Done
![image](https://user-images.githubusercontent.com/89875524/172370926-d7737338-2b1a-4910-b23e-cabb34d8a0b3.png)
![image](https://user-images.githubusercontent.com/89875524/172373579-3c55bc35-2f4b-4d12-a88d-3506c925e133.png)
![image](https://user-images.githubusercontent.com/89875524/172371226-288ae5a5-a84f-42e2-8291-07869f823baf.png)
![image](https://user-images.githubusercontent.com/89875524/172374933-a2c7202b-2e5e-47f5-bebe-b4c1b94cb7e9.png)
![image](https://user-images.githubusercontent.com/89875524/172374985-999d851b-0525-483a-bebf-d76ab85eb851.png)
![image](https://user-images.githubusercontent.com/89875524/172375880-957dc917-0dfb-4a1d-945a-bc57ff825264.png)
![image](https://user-images.githubusercontent.com/89875524/172377726-aed1fc4d-ce90-49e8-9ecb-43d07dda465b.png)
